<?php
// This page begins the session
session_start(); // Start a session.


?>
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8" />
      <meta name="description" content="PHP and SQL" />
      <meta name="keywords" content="HTML, PHP, SQL" />
      <meta name="author" content="Group"  />
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link href="styles/layout.css" rel="stylesheet" media="screen and (min-width:480px)"/>
      <link href="styles/mobile.css" rel="stylesheet" media="screen and (max-width:480px)"/> 
      <title>PHP Quiz</title>
   </head>
   <body>
      <header>
         <h1 class="animetitle">PHP</h1> 
     </header>