</main>
    <footer>
        <ul>
        <li>© Copyright Group 3</li>
        <li><a href="mailto:103355169@student.swin.edu.au"> Mark</a></li>
        <li><a href="mailto:103576290@student.swin.edu.au"> Stuart</a></li>
        <li><a href="mailto:104021872@student.swin.edu.au"> Jordan</a></li>
        <li><a href="mailto:104023496@student.swin.edu.au"> Brian</a></li>
        <li><a href="mailto:103999253@student.swin.edu.au"> Darren</a></li>
        </ul>
    </footer>
    </body>
    </html>